### ISSUE TITLE
I can haz CommonJS?

### ISSUE THREAD

**Issue by jrnail23** [velipso/polybool#1]
Hi @velipso, just wondering, is there any chance I can talk you into adding a CommonJS build for `@velipso/polybool`?

We want to adopt the TypeScript version (moving from the original `polybooljs`) so we can apply the Epsilon fix from https://github.com/velipso/polybooljs/pull/8, but we're not yet in a position to use ESM-only modules for our NodeJS app.

**Comment by velipso** [comment]
I just pushed v1.1.0 which has CommonJS support, let me know if that worked, I'm not an expert at CJS/ESM and ChatGPT helped lol 😄

**Comment by jrnail23** [comment]
Oh wow, thanks for that! I just got around to checking my notifications, so I'll give it a try and let you know how it goes.

**Comment by jrnail23** [comment]
@velipso, sorry, no luck.  It doesn't work for 2 reasons that I can tell (and I may be wrong here!):

1. The `@velipso/polybool` package.json file has `"type": "module"` -- AFAIK, typically you'd need a separate `dist/cjs/package.json` file with `"type": "commonjs"` in it to enable CommonJS usage.  
2. The `exports` field is incorrect -- `"require": "./dist/polybool.cjs.js"` should be  `"require": "./dist/polybool.cjs"`, since that's what's actually in the `dist` dir.

I can't lie to you, publishing hybrid (ESM + CJS) TypeScript packages is **tough** to get right.

If you're interested in getting it working properly, you should have a look at [tshy](https://www.npmjs.com/package/tshy).
